### ISSUE TITLE
Missaligned Columns

### ISSUE THREAD

**Issue by Plonus** [TatuLund/GridEditorColumnFix#4]
Hello Tatu,

i have a small sample application with your addons FastNavigation Addon and GridEitorColumnFix and can still reproduce missaligned columnlayout in MultiSelect Grid (see print screen).

If you navigate between the rows using the arrow keys or by clicking in the remarks column the layout breaks.
![sample](https://user-images.githubusercontent.com/41110709/109499998-f2f83280-7a95-11eb-9440-694a1442d21b.GIF)

[vaadin-app.zip](https://github.com/TatuLund/GridEditorColumnFix/files/6061709/vaadin-app.zip)
 Can you please have a look into it?

**Comment by Plonus** [comment]
A small note, if i deactivate the addon since it should be included in the fastNavigationAddon the first row breaks, otherwise the second one breaks after navigating with the arrow keys or by clicking in the remarks column between the two rows.

**Comment by Plonus** [comment]
Also I had a small conversation with Markus from the Vaadin support. He said you said using both addons shouldnt be necessary, so the best option would be to investigate and fix this bug in the FastNavigationAddon.

**Comment by TatuLund** [comment]
This is fixed by https://github.com/TatuLund/GridEditorColumnFix/commit/44fa53a8190dfd8e9c5fc56af20ef466a4723b0e

And released in Directory 0.3.6

The same fix is incorporated in GirdFastNavigation 2.6.3 as well https://vaadin.com/directory/component/gridfastnavigation-add-on
